wip
```
java.lang.UnsupportedOperationException: Unsupported access to ActorContext from the outside of Actor[akka://main/user#0]. No message is currently processed by the actor, but ActorContext was called from Thread[main-akka.actor.default-dispatcher-6,5,run-main-group-0].

	at akka06.ActiveClient$.$anonfun$generate$1(ActiveClient.scala:36)
```